#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/flow-monitor-helper.h"
#include "ns3/ipv4-flow-classifier.h"
#include "ns3/error-model.h"
#include <iostream>
#include <fstream>

using namespace ns3;

NS_LOG_COMPONENT_DEFINE ("ZkpLivelockSimulation");

int main (int argc, char *argv[])
{
  uint32_t nNodes = 10;
  uint32_t payloadSize = 64; // In Bytes
  double lambdaGlobal = 50.0; // 50Hz UR5 Kinematic Loop
  double ewJammingRate = 0.0; // Electronic Warfare packet drop rate (0.0 to 1.0)

  CommandLine cmd (__FILE__);
  cmd.AddValue ("nNodes", "Number of ZKP Edge Nodes generating the load", nNodes);
  cmd.AddValue ("payloadSize", "Cryptographic Payload Size in Bytes (64 for ECDSA/ZKP)", payloadSize);
  cmd.AddValue ("lambdaGlobal", "Global Arrival Rate / Kinematic Speed in Hz (Default: 50.0)", lambdaGlobal);
  cmd.AddValue ("ewJammingRate", "Electronic Warfare Packet Loss Ratio (0.0 to 1.0)", ewJammingRate);
  cmd.Parse (argc, argv);

  // 1. Empirical Mapping of Service Rate (mu) based on C-Wrapper Profiling (Test B)
  // The pristine, unadulterated mean service time (mu_time) is 9.6496 ms.
  // mu (pkts/sec) = 1.0 / 0.0096496 = 103.63
  double mu = 103.63;
  
  // Calculate the physical hardware bottleneck DataRate (Bits Per Second)
  // DataRate = mu (packets/sec) * payloadSize (bytes/packet) * 8 (bits/byte)
  double nodeBandwidthBps = mu * payloadSize * 8.0;

  // 2. Topology Setup
  // We use a Star topology: nNodes (Arduinos) connected to 1 Central Broker (Pi 4).
  NodeContainer brokerNode;
  brokerNode.Create(1);
  
  NodeContainer edgeNodes;
  edgeNodes.Create(nNodes);

  InternetStackHelper stack;
  stack.Install(brokerNode);
  stack.Install(edgeNodes);

  // 3. Bottleneck Link Configuration (The Pi 4 M/D/1 Limit)
  PointToPointHelper p2p;
  // This physically chokes the NS-3 link to mimic the Cortex-A72 deterministic calculation time
  p2p.SetDeviceAttribute("DataRate", DataRateValue(DataRate(nodeBandwidthBps)));
  p2p.SetChannelAttribute("Delay", StringValue("2ms"));
  
  // Apply QoS Drop Buffer (KEEP_LAST Depth=1 logic)
  // A small queue models the aggressive packet shedding proven in Test A
  p2p.SetQueue("ns3::DropTailQueue<Packet>", "MaxSize", StringValue("1p"));

  Ipv4AddressHelper address;
  std::vector<Ipv4InterfaceContainer> interfaces;
  std::vector<NetDeviceContainer> allDevices;

  // Connect Broker to all Edge Nodes
  for (uint32_t i = 0; i < nNodes; i++) {
    NodeContainer link(edgeNodes.Get(i), brokerNode.Get(0));
    NetDeviceContainer devices = p2p.Install(link);
    allDevices.push_back(devices);
    
    std::ostringstream subnet;
    subnet << "10.1." << i + 1 << ".0";
    address.SetBase(subnet.str().c_str(), "255.255.255.0");
    interfaces.push_back(address.Assign(devices));
  }

  // 4. Electronic Warfare (EW) Error Model Injection
  // We attach a RateErrorModel to the Broker's receiving devices to simulate physical RF jamming
  if (ewJammingRate > 0.0) {
    Ptr<RateErrorModel> em = CreateObject<RateErrorModel>();
    em->SetAttribute("ErrorRate", DoubleValue(ewJammingRate));
    for (uint32_t i = 0; i < nNodes; i++) {
      // Apply error model to the Broker's device (index 1 of the link)
      allDevices[i].Get(1)->SetAttribute("ReceiveErrorModel", PointerValue(em));
    }
  }

  // 5. Traffic Generation (The DDS Kinematic Stream)
  // The global 50Hz stream is generated by the N edge nodes and sent to the Broker.
  double lambdaPerNode = lambdaGlobal / nNodes;
  double trafficRateBps = lambdaPerNode * payloadSize * 8.0;
  std::ostringstream trafficRateStr;
  trafficRateStr << trafficRateBps << "bps";

  uint16_t port = 9;
  
  // Broker acts as Sink
  PacketSinkHelper sink("ns3::UdpSocketFactory", InetSocketAddress(Ipv4Address::GetAny(), port));
  ApplicationContainer sinkApp = sink.Install(brokerNode.Get(0));
  sinkApp.Start(Seconds(0.0));
  sinkApp.Stop(Seconds(10.0));

  // Edge Nodes act as Clients blasting the Broker
  for (uint32_t i = 0; i < nNodes; i++) {
    // The Broker is IP address index 1 (0 is network)
    OnOffHelper onoff("ns3::UdpSocketFactory", InetSocketAddress(interfaces[i].GetAddress(1), port));
    onoff.SetConstantRate(DataRate(trafficRateStr.str()), payloadSize);
    
    ApplicationContainer clientApp = onoff.Install(edgeNodes.Get(i));
    clientApp.Start(Seconds(1.0));
    clientApp.Stop(Seconds(9.0));
  }

  // 6. Flow Monitor to track Livelock and Queue Saturation
  FlowMonitorHelper flowmon;
  Ptr<FlowMonitor> monitor = flowmon.InstallAll();

  Simulator::Stop(Seconds(10.0));
  Simulator::Run();

  monitor->CheckForLostPackets();
  Ptr<Ipv4FlowClassifier> classifier = DynamicCast<Ipv4FlowClassifier>(flowmon.GetClassifier());
  std::map<FlowId, FlowMonitor::FlowStats> stats = monitor->GetFlowStats();

  uint32_t totalTx = 0;
  uint32_t totalRx = 0;
  uint32_t totalDropped = 0;
  double totalDelay = 0.0;

  for (std::map<FlowId, FlowMonitor::FlowStats>::const_iterator i = stats.begin(); i != stats.end(); ++i) {
    totalTx += i->second.txPackets;
    totalRx += i->second.rxPackets;
    totalDropped += i->second.lostPackets;
    if (i->second.rxPackets > 0) {
      totalDelay += i->second.delaySum.GetSeconds();
    }
  }

  double avgDelayMs = (totalRx > 0) ? (totalDelay / totalRx) * 1000.0 : 0.0;
  double dropRate = (totalTx > 0) ? ((double)totalDropped / totalTx) * 100.0 : 0.0;

  // 7. Mathematical Thesis Output
  std::cout << "\n==================================================================" << std::endl;
  std::cout << "          M/D/1 QUEUE SATURATION SIMULATION (EW JAMMING)          " << std::endl;
  std::cout << "==================================================================" << std::endl;
  std::cout << "Payload Size       : " << payloadSize << " Bytes" << std::endl;
  std::cout << "Active Edge Nodes  : " << nNodes << std::endl;
  std::cout << "EW Jamming Rate    : " << (ewJammingRate * 100.0) << "% Packet Loss" << std::endl;
  std::cout << "Service Rate (μ)   : " << mu << " pkts/sec (Total System Capacity)" << std::endl;
  std::cout << "Arrival Rate (λ)   : " << lambdaGlobal << " pkts/sec (Aggregated Global)" << std::endl;
  std::cout << "Traffic Intensity  : " << lambdaGlobal / mu << " (ρ = λ / μ)" << std::endl;
  std::cout << "------------------------------------------------------------------" << std::endl;
  std::cout << "Packets Sent       : " << totalTx << std::endl;
  std::cout << "Packets Received   : " << totalRx << std::endl;
  std::cout << "Packets Dropped    : " << totalDropped << " (" << dropRate << "% Drop Rate)" << std::endl;
  std::cout << "Average Queue Delay: " << avgDelayMs << " ms" << std::endl;
  
  if (dropRate > (ewJammingRate * 100.0) + 1.0 || (lambdaGlobal / mu) >= 1.0) {
    std::cout << "\n[RESULT] SYSTEM SATURATED! Traffic Intensity ρ > 1.0." << std::endl;
    std::cout << "The M/D/1 Queue cannot keep up. Data loss exceeds pure EW Jamming." << std::endl;
  } else {
    std::cout << "\n[RESULT] SYSTEM STABLE! Traffic Intensity ρ < 1.0." << std::endl;
    std::cout << "The deterministic cluster successfully load-balanced the stream." << std::endl;
  }
  std::cout << "==================================================================\n" << std::endl;

  // 8. CSV Export for Thesis Graphs
  std::ofstream csvFile;
  csvFile.open("simulation_results.csv", std::ios_base::app); // Append mode
  // If file is empty, write header
  std::ifstream checkFile("simulation_results.csv");
  checkFile.seekg(0, std::ios::end);
  if (checkFile.tellg() == 0) {
      csvFile << "Nodes,PayloadSize,ServiceRate,ArrivalRate,TrafficIntensity,AvgDelayMs,DropRate,EWJammingRate,SystemCrash\n";
  }
  checkFile.close();
  
  int systemCrash = (dropRate > (ewJammingRate * 100.0) + 1.0 || (lambdaGlobal / mu) >= 1.0) ? 1 : 0;
  
  csvFile << nNodes << "," << payloadSize << "," << mu << "," << lambdaGlobal << "," << (lambdaGlobal / mu) << "," << avgDelayMs << "," << dropRate << "," << ewJammingRate << "," << systemCrash << "\n";
  csvFile.close();
  std::cout << "Results appended to simulation_results.csv" << std::endl;

  Simulator::Destroy();
  return 0;
}
