#!/usr/bin/env python3
import random
import time
import subprocess
import json
import os

# --- 10-DAY HITL THESIS ORCHESTRATOR ---
# Generates the 60-trial Latin Square Randomized Matrix
# Prompts operator for manual UR5 resets (Category 0 Halt requirement)

# 1. Define the Matrix
ALGORITHMS = ["ZKP", "ECC"]
SCALES = [3, 10]
LOSS_RATES = [0, 10, 20] # Percent
TRIALS_PER_CONDITION = 5

def generate_randomized_matrix():
    matrix = []
    for alg in ALGORITHMS:
        for scale in SCALES:
            for loss in LOSS_RATES:
                for t in range(TRIALS_PER_CONDITION):
                    matrix.append({
                        "algorithm": alg,
                        "n_nodes": scale,
                        "loss_rate": loss
                    })
    random.shuffle(matrix)
    return matrix

def inject_network_loss(loss_rate):
    """
    Applies Linux Traffic Control (tc) rules to the Raspberry Pi's eth0 interface.
    This simulates the degraded DIL environment.
    """
    print(f"\n[ORCHESTRATOR] Applying tc netem rule: {loss_rate}% packet loss...")
    # Clean up old rules first
    subprocess.run(["sudo", "tc", "qdisc", "del", "dev", "eth0", "root"], stderr=subprocess.DEVNULL)
    
    if loss_rate > 0:
        cmd = ["sudo", "tc", "qdisc", "add", "dev", "eth0", "root", "netem", "loss", f"{loss_rate}%"]
        subprocess.run(cmd)

def main():
    print("==================================================")
    print("      HITL UR5 PHYSICAL CAMPAIGN ORCHESTRATOR     ")
    print("==================================================")
    
    matrix = generate_randomized_matrix()
    total_trials = len(matrix)
    print(f"Generated {total_trials} randomized trials.")
    
    # Track progress in a JSON file in case of crash
    progress_file = "orchestrator_progress.json"
    start_idx = 0
    if os.path.exists(progress_file):
        with open(progress_file, 'r') as f:
            data = json.load(f)
            start_idx = data.get("completed_trials", 0)
            print(f"Resuming from trial {start_idx + 1}")
    
    for i in range(start_idx, total_trials):
        condition = matrix[i]
        print("\n--------------------------------------------------")
        print(f" TRIAL [{i+1}/{total_trials}] - SETUP")
        print(f" Algorithm: {condition['algorithm']} | Scale: n={condition['n_nodes']} | Loss: {condition['loss_rate']}%")
        print("--------------------------------------------------")
        
        # 1. Inject Network Degradation
        inject_network_loss(condition['loss_rate'])
        
        # 2. Operator Block (Manual UR5 Reset)
        print("\n>>> CONDITION SET. MANUAL UR5 REBOOT REQUIRED. <<<")
        print(">>> 1. Clear Safeguard Stop on Teach Pendant")
        print(">>> 2. Power On Servos & Release Brakes")
        print(">>> 3. Press PLAY on the Teach Pendant")
        input("\n>>> ARM ROBOT AND PRESS ENTER TO COMMENCE TRIAL <<<")
        
        # 3. Kinematic Spool-up
        print("\n[ORCHESTRATOR] Spooling up UR5 Kinematics...")
        # We assume the driver and logger are already running in other tmux/terminals.
        # We start the stream_wrist_kinematics node in a subprocess.
        kinematics_proc = subprocess.Popen(
            ["ros2", "run", "sentry_logic", "stream_wrist_kinematics"]
        )
        
        print("[ORCHESTRATOR] Holding for 8-second EWMA stabilization...")
        time.sleep(8)
        
        # 4. The Strike & Log
        print("[ORCHESTRATOR] Injecting Byzantine Attack Payload via ROS 2 Service!")
        # Call the new /inject_attack service exposed by joint_logger_node
        subprocess.run(["ros2", "service", "call", "/inject_attack", "std_srvs/srv/Trigger"])
        
        print("[ORCHESTRATOR] Attack sent. Waiting for UR5 Category 0 Halt...")
        time.sleep(3) # Give it a moment to process the drop and save the CSV
        
        # 5. Cleanup
        print("[ORCHESTRATOR] Terminating kinematic streamer for next cycle...")
        kinematics_proc.terminate()
        kinematics_proc.wait()
        
        # Save progress
        with open(progress_file, 'w') as f:
            json.dump({"completed_trials": i + 1, "last_condition": condition}, f)
            
        print(f"[ORCHESTRATOR] Trial {i+1} complete. CSV generated by logger.")

    print("\n==================================================")
    print(" CAMPAIGN COMPLETE. PROCEED TO POWER ANALYSIS. ")
    print("==================================================")
    # Final cleanup
    subprocess.run(["sudo", "tc", "qdisc", "del", "dev", "eth0", "root"], stderr=subprocess.DEVNULL)

if __name__ == '__main__':
    main()
