[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git

build_flags =
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16