[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git

lib_ignore = WiFi

; Force-link the pre-compiled micro-ROS library that PlatformIO misses
build_flags =
    -L.pio/libdeps/nano33ble/micro_ros_arduino/src/cortex-m4
    -lmicroros