; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200

# Tell PlatformIO to download micro-ROS
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

# Tell the micro-ROS builder what we are doing
board_microros_transport = serial
board_microros_distro = humble
